default_stages: [push, commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9  # frozen: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude_types: [text]
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: c5e8fa75dda5f764d20f66a215d71c21cfa198e1  # frozen: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: [ --line-length=120 ]
  - repo: https://github.com/psf/black
    rev: 27d20144a7517594e24a1649451177b2a11284be  # frozen: 22.10.0
    hooks:
      - id: black
        args: [ --config=pyproject.toml ]
  - repo: https://github.com/executablebooks/mdformat
    rev: 82f84976fc57d5ae61cbf2d457a26a89d4b4eef4  # frozen: 0.7.16
    hooks:
      - id: mdformat
        exclude: .azuredevops/
        additional_dependencies:
          - mdformat-black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: '0b037c2b59aa62dc3be3287d175295f1a5547eb9'  # frozen: v0.991
    hooks:
      - id: mypy
        args: [--config-file, pyproject.toml]   #[ --namespace-packages, --explicit-package-bases, --ignore-missing-imports, --allow-untyped-global, --install-types, --non-interactive]  #[--config-file, cloud-sdk/mypy.ini]
        stages: [manual]
  - repo: https://github.com/PyCQA/bandit
    rev: 1ed79063e3672a1c6d91ee27cb648e07a7465344  # frozen: 1.7.4
    hooks:
      - id: bandit
        args: [ --exclude, "*/tests/**,tests/**,**.md,**.txt,**.in", -f, json, -o, bandit_res.json ]
        stages: [manual]
